[package]
name = "virtual-adapter"
publish = false
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["wasi-0_2_x"]
debug = []
wasi-0_2_x = [] # use wasi:*@0.2.12

[dependencies]
anyhow = { workspace = true, default-features = false }
wit-bindgen = { workspace = true, features = ["macros"] }
