[package]
name = "virtual-adapter"
publish = false
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["wasi-p2"]
debug = []
wasi-p2 = [] # use wasi:*@0.2.12

[dependencies]
anyhow = { workspace = true, default-features = false }
wit-bindgen = { workspace = true, features = ["macros"] }
